require 'fileutils'
require 'open-uri'

xml = ARGV[0]
FileUtils.rm_rf('tmp/'+ARGV[1]+'')
FileUtils::mkdir_p 'tmp/'+ARGV[1]+''
doc = open(xml).read
style = doc.scan(/<style.+>/)

ardoc = doc.split('<div xml')
ardoc.shift
ardoc.each do |rsub|
	stfile = []
	stfile << '[Script Info]'
	stfile << '; Script generated by Aegisub 3.2.2'
	stfile << '; http://www.aegisub.org/'
	stfile << 'Title: TaigaSubs'
	stfile << 'ScriptType: v4.00+'
	stfile << 'WrapStyle: 0'
	stfile << 'ScaledBorderAndShadow: yes'
	stfile << 'YCbCr Matrix: TV.601'
	stfile << 'PlayResX: 640'
	stfile << 'PlayResY: 480'
	stfile << ''
	stfile << '[Aegisub Project Garbage]'
	stfile << ''
	stfile << '[V4+ Styles]'
	stfile << 'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding'
	stfile << 'Style: taiga_1,Arimo,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1.7,1,2,0,0,25,1'
	stfile << ''
	stfile << '[Events]'
	stfile << 'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'
	lang = rsub.scan(/\".+\"/)[0].gsub('"','')
	rsub.split('<p begin')[1...-1].each do |subline|
		time = subline.scan(/\d\d:\d\d:\d\d\.\d\d\d/)
		start = time[0]
		endtime = time[1]
		style = 'taiga_'+subline[/style=\".+\"/].gsub('style=','').gsub('"','')
		txtx = subline[/>(.|\r|\n)+<\/p>/].gsub("\n",'').gsub("\r",'').gsub("\t",'')[1..-5]
		
		p txtx
		stmp = 'Dialogue: 0,'+start[1..-2]+','+endtime[1..-2]+','+style+',,0,0,0,,'+txtx.gsub('<br />','\N').gsub('<br/>','\N')
		stfile << stmp
		
	end
	stfile.each do |str|
		File.open('tmp/'+ARGV[1]+'/sub.'+lang+'.ass', 'a'){ |file| file.puts  str }
	end
end


